//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::category_tbl;
use crate::entity::store_category_tbl;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "category_tbl")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = true)]
    pub category_seq: i32,
    pub category_group_code: String,
    pub category_group_name: String,
    pub category_name: String,
    pub category_icon: Option<String>,
    pub reg_dt: DateTime,
    pub chg_dt: Option<DateTime>,
    pub reg_id: String,
    pub chg_id: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::store_category_tbl::Entity")]
    StoreCategoryTbl,
}

impl Related<store_category_tbl::Entity> for category_tbl::Entity {
    fn to() -> RelationDef {
        Relation::StoreCategoryTbl.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
