//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

use sea_orm::entity::prelude::*;

use crate::entity::zero_possible_market;
use crate::entity::store_recommend_tbl;
use crate::entity::store;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "store")]
pub struct Model {
    pub name: String,
    pub r#type: Option<String>,
    pub address: Option<String>,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))")]
    pub lat: Decimal,
    #[sea_orm(column_type = "Decimal(Some((10, 7)))")]
    pub lng: Decimal,
    pub reg_dt: Option<DateTime>,
    pub reg_id: Option<String>,
    pub chg_dt: Option<DateTime>,
    pub chg_id: Option<String>,
    #[sea_orm(primary_key)]
    pub seq: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_one = "super::zero_possible_market::Entity")]
    ZeroPossibleMarket,
    #[sea_orm(has_many = "super::store_recommend_tbl::Entity")]
    StoreRecommendTbl,
}

impl Related<zero_possible_market::Entity> for store::Entity {
    fn to() -> RelationDef {
        Relation::ZeroPossibleMarket.def()
    }
}

impl Related<store_recommend_tbl::Entity> for store::Entity {
    fn to() -> RelationDef {
        Relation::StoreRecommendTbl.def()
    }
}


impl ActiveModelBehavior for ActiveModel {}
