//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.5

pub mod prelude;

pub mod migrations;
pub mod recommend_tbl;
pub mod store;
pub mod store_backup;
pub mod store_recommend_tbl;
pub mod zero_possible_market;
pub mod zero_possible_market_backup;
